# -*- coding: utf-8 -*-
"""automated_report_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-72PoFgM8-mIgbKFUcBy8LdfMsRt0Xv
"""

with open("data.csv", "w") as f:
    f.write("""Name,Score
Alice,85
Bob,92
Charlie,78
David,90
Eve,88
Frank,75
Grace,95
Hannah,82
Ian,87
Jack,91""")

!pip install fpdf

import pandas as pd
from fpdf import FPDF

# Read data from CSV file
data = pd.read_csv("data.csv")

# Perform basic analysis
average_score = data['Score'].mean()
max_score = data['Score'].max()
min_score = data['Score'].min()

# PDF Report Class
class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Student Score Report', border=False, ln=True, align='C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

# Create PDF
pdf = PDFReport()
pdf.add_page()
pdf.set_font("Arial", size=12)

# Add table header
pdf.set_font("Arial", 'B', 12)
pdf.cell(50, 10, "Name", 1)
pdf.cell(50, 10, "Score", 1)
pdf.ln()

# Add table rows
pdf.set_font("Arial", size=12)
for index, row in data.iterrows():
    pdf.cell(50, 10, row['Name'], 1)
    pdf.cell(50, 10, str(row['Score']), 1)
    pdf.ln()

# Add analysis summary
pdf.ln(10)
pdf.set_font("Arial", 'B', 12)
pdf.cell(0, 10, "Summary:", ln=True)
pdf.set_font("Arial", size=12)
pdf.cell(0, 10, f"Average Score: {average_score:.2f}", ln=True)
pdf.cell(0, 10, f"Highest Score: {max_score}", ln=True)
pdf.cell(0, 10, f"Lowest Score: {min_score}", ln=True)

# Save the PDF report
pdf.output("report.pdf")

print("PDF report generated successfully as report.pdf")

from google.colab import files
files.download('report.pdf')